### ISSUE TITLE
iOS7 Support

### ISSUE THREAD

**Issue by confile** [notbenoit/SCCollectionViewController#1]
Is it possible to make this great project run on IOS7 as well?

**Comment by notbenoit** [comment]
Hi ! 
I pushed a 1.0.1 version with a deployment target of 7.0+.
I did not try it on a real device, let me know if it's ok for you.

The only change made was using the mask property on CALayer instead of the new maskView property on UIView.

**Comment by confile** [comment]
It is working now.
