### ISSUE TITLE
Custom UICollectionViewCell?

### ISSUE THREAD

**Issue by andersonkxiass** [notbenoit/SCCollectionViewController#2]
Hey,

I'm trying to use your lib, but I have not figured out how to use my own UICollectionViewCell. You can show an example of how to do this?

thanks in advance!

**Comment by notbenoit** [comment]
Hi!
This collection controller is not ready to host any subclass of UICollectionViewCell. To be honest, it's a limitation and a design mistake I made when creating this library.
If I have some time, I will write an improved generic version which will work for any UICollectionViewCell subclass.

For now, you can add any subview you want to the cell passed in the `configureCell:` closure.
Or, you can use the sources in you own project, and change the cell which is registered here : 
`self.collectionView.registerClass(UICollectionViewCell.self, forCellWithReuseIdentifier: reuseIdentifier)` or register a nib with `registerNib`

**Comment by andersonkxiass** [comment]
I'm already using the source within my project, I saw that the code is very clean!

I changed the SCCollectionViewController class in my project to support custom UICollectionViewCell if you do not to mind I can submit a pull request  with these changes.

thanks in advance!
